{
  "tests/test_with_pytest.py::test_always_fails": true
}